import { motion } from 'framer-motion'
import { socialEndpoints } from '../config/docsConfig'
import EndpointBadge from '../components/EndpointBadge'
import CodeBlock from '../components/CodeBlock'
import ParamTable from '../components/ParamTable'
import StatusTable from '../components/StatusTable'
import DocsPager from '../components/DocsPager'

const EASE = [0.16, 1, 0.3, 1] as const

const PLATFORMS = [
  { id: 'x', name: 'X (Twitter)', color: '#e7e9ea', status: 'Available' },
  { id: 'discord', name: 'Discord', color: '#5865f2', status: 'Available' },
  { id: 'mastodon', name: 'Mastodon', color: '#6364ff', status: 'Available' },
  { id: 'linkedin', name: 'LinkedIn', color: '#0a66c2', status: 'Available' },
]

export default function SocialAccountsSection() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, ease: EASE }}
    >
      <div className="mb-10">
        <h1 className="text-3xl font-bold tracking-tight text-text-primary mb-3" id="social-accounts">
          Social Accounts
        </h1>
        <p className="text-text-secondary leading-relaxed mb-6">
          Before publishing, you must link at least one social platform to your account using OAuth2.
          The flow is: initialize → redirect user → callback. Once linked, the platform is available
          for publishing via the Posts API.
        </p>

        <div className="rounded-xl border border-border overflow-hidden mb-6">
          <div className="border-b border-border px-4 py-2.5 bg-surface-2/40">
            <p className="text-xs font-semibold uppercase tracking-wide text-text-tertiary">Supported Platforms</p>
          </div>
          <div className="divide-y divide-border">
            {PLATFORMS.map(({ id, name, color, status }) => (
              <div key={id} className="flex items-center justify-between px-4 py-3">
                <div className="flex items-center gap-3">
                  <span
                    className="w-2 h-2 rounded-full shrink-0"
                    style={{ backgroundColor: color }}
                  />
                  <span className="text-sm font-mono text-text-secondary">{id}</span>
                  <span className="text-sm text-text-tertiary">{name}</span>
                </div>
                <span className={`text-xs rounded-full px-2.5 py-0.5 font-medium ${
                  status === 'Available'
                    ? 'bg-emerald-500/10 text-emerald-400'
                    : 'bg-surface-2 text-text-tertiary'
                }`}>
                  {status}
                </span>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-xl border border-violet-500/20 bg-violet-500/5 px-4 py-3 mb-4">
          <p className="text-sm text-violet-400/80 leading-relaxed">
            <strong className="text-violet-400">OAuth2 State:</strong> The state token generated by the
            initialize endpoint is stored server-side for 5 minutes. Always include it in the callback to
            prevent CSRF attacks.
          </p>
        </div>

        <div className="rounded-xl border border-violet-500/20 bg-violet-500/5 px-4 py-3">
          <p className="text-sm text-violet-400/80 leading-relaxed">
            <strong className="text-violet-400">Mastodon instances:</strong> Mastodon is federated, so it
            requires a <code className="font-mono text-violet-300">platform_instance</code> parameter
            naming the server to connect (e.g. <code className="font-mono text-violet-300">mastodon.social</code>).
            Pass it on both the login-URL and link requests. Currently supported:{' '}
            <code className="font-mono text-violet-300">mastodon.social</code>. Additional instances
            (fosstodon.org, mastodon.online) are rolling out.
          </p>
        </div>
      </div>

      {socialEndpoints.map((ep, i) => (
        <motion.section
          key={ep.id}
          id={ep.id}
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: i * 0.06, duration: 0.3, ease: EASE }}
          className="mb-14 scroll-mt-24"
        >
          <div className="flex items-start justify-between gap-4 mb-3 flex-wrap">
            <h2 className="text-xl font-semibold text-text-primary">{ep.title}</h2>
            {ep.authRequired && (
              <span className="shrink-0 rounded-full border border-amber-500/20 bg-amber-500/10 px-3 py-1 text-xs text-amber-400">
                Auth required
              </span>
            )}
          </div>
          <EndpointBadge method={ep.method} path={ep.path} className="mb-4" />
          <p className="text-sm text-text-secondary leading-relaxed mb-6">{ep.description}</p>

          {ep.params && ep.params.length > 0 && <ParamTable params={ep.params} />}

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {ep.requestExample && (
              <CodeBlock code={ep.requestExample} language="json" title="Request body" />
            )}
            {ep.responseExample && (
              <CodeBlock code={ep.responseExample} language="json" title="Response" />
            )}
          </div>

          <StatusTable codes={ep.statusCodes} />
        </motion.section>
      ))}

      <DocsPager currentSlug="social-accounts" />
    </motion.div>
  )
}
