"""add_webhook_url_coulmn_to_social_account

Revision ID: 316520745890
Revises: 9afd5263314b
Create Date: 2026-06-20 08:24:29.974794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316520745890'
down_revision: Union[str, Sequence[str], None] = '9afd5263314b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'webhook_url')
    # ### end Alembic commands ###
