"""add_index_to_hashed_api_key_field_for_fast_lookups

Revision ID: 32bdcc1245f3
Revises: c7622f55992c
Create Date: 2026-06-12 06:50:02.018988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bdcc1245f3'
down_revision: Union[str, Sequence[str], None] = 'c7622f55992c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
