"""add_auth_provider_nullable_password

Revision ID: 6793f672c067
Revises: 47ba39c3990e
Create Date: 2026-06-09 15:30:27.875663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6793f672c067'
down_revision: Union[str, Sequence[str], None] = '47ba39c3990e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    authvalues = sa.Enum('GOOGLE', 'GITHUB', 'LOCAL', name='authvalues')
    authvalues.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('auth_provider', sa.Enum('GOOGLE', 'GITHUB', 'LOCAL', name='authvalues'), nullable=False, server_default='LOCAL'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE authvalues')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
