"""add_profile_metadata

Revision ID: 7270d4e34f87
Revises: daf42f091b4b
Create Date: 2026-06-02 21:18:57.016913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7270d4e34f87'
down_revision: Union[str, Sequence[str], None] = 'daf42f091b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('profile_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'profile_metadata')
    # ### end Alembic commands ###
