"""add_is_active_field_to_social_account_for_soft_deletion

Revision ID: 9afd5263314b
Revises: 9ceb0dfd82ef
Create Date: 2026-06-16 09:06:19.585401

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9afd5263314b"
down_revision: Union[str, Sequence[str], None] = "9ceb0dfd82ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "social_accounts",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("social_accounts", "is_active")
    # ### end Alembic commands ###
