"""add_platform_instance_field_to_social_account_for_mastodon_support

Revision ID: 9ceb0dfd82ef
Revises: 3963d4f0adda
Create Date: 2026-06-16 06:49:05.017834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ceb0dfd82ef'
down_revision: Union[str, Sequence[str], None] = '3963d4f0adda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('platform_instance', sa.String(), nullable=True))
    op.drop_constraint(op.f('uix_platform_account'), 'social_accounts', type_='unique')
    op.create_unique_constraint('uix_platform_instance_account', 'social_accounts', ['platform', 'platform_instance', 'provider_account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_platform_instance_account', 'social_accounts', type_='unique')
    op.create_unique_constraint(op.f('uix_platform_account'), 'social_accounts', ['platform', 'provider_account_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('social_accounts', 'platform_instance')
    # ### end Alembic commands ###
