"""add_posts_tables

Revision ID: ac5856fa035f
Revises: 7270d4e34f87
Create Date: 2026-06-03 23:40:17.518494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac5856fa035f'
down_revision: Union[str, Sequence[str], None] = '7270d4e34f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_platform_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAIL', name='postresultstatus'), nullable=False),
    sa.Column('post_url', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    poststatus = sa.Enum('PENDING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', name='poststatus')
    poststatus.create(op.get_bind())
    op.add_column('posts', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', name='poststatus'), nullable=False))
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'is_published')
    op.alter_column('social_accounts', 'profile_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_accounts', 'profile_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('posts', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'options')
    op.drop_table('post_platform_results')
    # ### end Alembic commands ###
