"""add_account_profile_fields

Revision ID: daf42f091b4b
Revises: 0bbe65468e81
Create Date: 2026-06-02 20:49:27.241293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf42f091b4b'
down_revision: Union[str, Sequence[str], None] = '0bbe65468e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('username', sa.String(), nullable=True))
    op.add_column('social_accounts', sa.Column('global_name', sa.String(), nullable=True))
    op.add_column('social_accounts', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'avatar_url')
    op.drop_column('social_accounts', 'global_name')
    op.drop_column('social_accounts', 'username')
    # ### end Alembic commands ###
