"""
Authentication router handling user registration, login, and OAuth flows.

Endpoints:
    POST /register     — Register new user with email and password
    POST /login        — Authenticate and receive JWT tokens
    POST /refresh      — Refresh access token using refresh token
    POST /logout       — Revoke refresh token
    GET  /google/login     — Initialize Google OAuth2 flow
    GET  /google/callback  — Handle Google OAuth2 callback
    GET  /github/login     — Initialize GitHub OAuth2 flow
    GET  /github/callback  — Handle GitHub OAuth2 callback
"""

import secrets
from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.ext.asyncio import AsyncSession

from src.api.dependencies import RateLimiter
from src.auth.oauth2.github import GithubAuthProvider
from src.auth.oauth2.google import GoogleAuthProvider
from src.auth.schemas import (
    GithubUserCreate,
    GoogleUserCreate,
    RefreshTokenRequest,
    UserCreate,
)
from src.core.database import get_db
from src.core.redis import redis_client
from src.core.security import (
    create_access_token,
    create_refresh_token,
    get_user_from_refresh_token,
    revoke_refresh_token,
    verify_password,
)
from src.users.models import AuthValues, User
from src.users.repository import create_user, get_user_by_email
from src.users.schemas import UserResponse

router = APIRouter(
    tags=["Authentication"],
    dependencies=[Depends(RateLimiter(max_requests=60, window_seconds=60))],
)


@router.post(
    "/register", response_model=UserResponse, status_code=status.HTTP_201_CREATED
)
async def register(user_in: UserCreate, db: AsyncSession = Depends(get_db)) -> User:
    """
    Registers a new user in the system. It uses the generic email password authentication method.

    Args:
        user_in: The user data in the UserCreate schema format.
        db: Active database session for persisting the new user.

    Returns:
        UserResponse model with all the necessary user data.

    Raises:
        HTTPException 400: If user already exists in the system.
        HTTPException 500: If there is an internal server error.
    """
    existing_user = await get_user_by_email(db, user_in.email)
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="User with this email already exists",
        )

    try:
        new_user = await create_user(db, user_in)
        await db.commit()
        await db.refresh(new_user, attribute_names=["social_accounts"])
        return new_user
    except Exception as e:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An internal server error occured.",
        )


@router.post("/login")
async def login(
    form_data: OAuth2PasswordRequestForm = Depends(), db: AsyncSession = Depends(get_db)
) -> Dict[str, Any]:
    """
    Authenticates a user with their email and password.

    On successful authentication it generates access and refresh tokens.

    Args:
        form_data: This is the login form data obtained from the request.
        db: Active database session for persisting the new user.

    Returns:
        Dictionary containing:
            access_token: The token generated by create_access_token.
            refresh_token: The token generated by create_refresh_token.

    Raises:
        HTTPException 400: If user is using the wrong method for logging in.
        HTTPException 401: If the provided credentials are invalid.
    """
    user = await get_user_by_email(db, form_data.username)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )

    if user.auth_provider != AuthValues.LOCAL:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Please use {user.auth_provider.value} to login.",
        )

    if not user.hashed_password or not verify_password(
        form_data.password, user.hashed_password
    ):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )

    access_token = create_access_token(subject=str(user.id))
    refresh_token = await create_refresh_token(user_id=str(user.id))
    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer",
    }


@router.post("/refresh")
async def refresh_token(token_request: RefreshTokenRequest) -> Dict[str, Any]:
    """
    Generate a new access and refresh tokens using a valid refresh token.

    Implements refresh token rotation - the old token is revoked after a new one is issued.
    """

    user_id = await get_user_from_refresh_token(token_request.refresh_token)
    if not user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid refresh token",
        )
    try:
        access_token = create_access_token(subject=user_id)
        new_refresh_token = await create_refresh_token(user_id=user_id)
        await revoke_refresh_token(token_request.refresh_token)
        return {
            "access_token": access_token,
            "refresh_token": new_refresh_token,
            "token_type": "bearer",
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An internal server error occurred.",
        )


@router.post("/logout", status_code=status.HTTP_204_NO_CONTENT)
async def logout(token_request: RefreshTokenRequest):
    """Logs out the user by revoking the refresh token."""
    try:
        await revoke_refresh_token(token_request.refresh_token)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An internal server error occurred.",
        )


@router.get(
    "/google/login",
    dependencies=[Depends(RateLimiter(max_requests=10, window_seconds=60))],
)
async def google_oauth_login() -> Dict[str, str]:
    """
    Initialize Google OAuth2 flow.

    Returns:
        Dictionary containing authorization_url and state parameter.
    """
    google_provider = GoogleAuthProvider()
    state = secrets.token_urlsafe(32)
    await redis_client.setex(f"google_oauth_state:{state}", 300, "valid")

    authorization_url = await google_provider.get_authorization_url(state)
    return {"authorization_url": authorization_url, "state": state}


@router.get(
    "/google/callback",
    dependencies=[Depends(RateLimiter(max_requests=10, window_seconds=60))],
)
async def google_oauth_callback(
    code: str, state: str, db: AsyncSession = Depends(get_db)
) -> Dict[str, Any]:
    """
    Handles Google OAuth2 callback.

    Exchanges code for tokens and redirects user.
    Uses state verification for preventing csrf attacks.

    Args:
        code: The authorization code obtained from the auth provider.
        state: The token used for preventing csrf attacks.

    Returns:
        Dictionary containing:
            access_token: The access token for the user.
            refresh_token: The refresh token for the user.
            token_type: The type of token.
    Raises:
        HTTPException 400: If state token is expired or invalid or if fetching
        email from google fails or the email is already registered with a different auth_provider.
        HTTPException 500: If internal server error occurs.
    """
    stored_state = await redis_client.get(f"google_oauth_state:{state}")

    if not stored_state:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid or expired state parameter",
        )

    await redis_client.delete(f"google_oauth_state:{state}")

    google_provider = GoogleAuthProvider()
    user_info = await google_provider.exchange_code_for_token(code)
    email = user_info.get("email")

    if not email:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Failed to retrieve email from Google",
        )

    user = await get_user_by_email(db, email)

    if user and user.auth_provider != AuthValues.GOOGLE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email is already registered with a different authentication provider.",
        )
    try:
        if not user:
            user_in = GoogleUserCreate(
                email=email, password=None, auth_provider=AuthValues.GOOGLE
            )
            user = await create_user(db, user_in)
            await db.commit()

        await db.refresh(user)
        access_token = create_access_token(subject=str(user.id))
        refresh_token = await create_refresh_token(user_id=str(user.id))

        return {
            "access_token": access_token,
            "refresh_token": refresh_token,
            "token_type": "bearer",
        }

    except HTTPException:
        raise
    except Exception as e:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An internal server error occurred.",
        )


@router.get(
    "/github/login",
    dependencies=[Depends(RateLimiter(max_requests=10, window_seconds=60))],
)
async def github_oauth_login() -> Dict[str, str]:
    """
    Initialize Github OAuth2 flow.

    Returns:
        Dictionary containing authorization_url and state parameter.
    """
    github_provider = GithubAuthProvider()
    state = secrets.token_urlsafe(32)

    authorization_url = await github_provider.get_authorization_url(state)

    return {"authorization_url": authorization_url, "state": state}


@router.get(
    "/github/callback",
    dependencies=[Depends(RateLimiter(max_requests=10, window_seconds=60))],
)
async def github_oauth_callback(
    code: str, state: str, db: AsyncSession = Depends(get_db)
) -> Dict[str, Any]:
    """
    Handles Github OAuth2 callback.

    Exchanges code for tokens and redirects user.
    Uses state verification for preventing csrf attacks.

    Args:
        code: The authorization code obtained from the auth provider.
        state: The token used for preventing csrf attacks.

    Returns:
        Dictionary containing:
            access_token: The access token for the user.
            refresh_token: The refresh token for the user.
            token_type: The type of token.
    Raises:
        HTTPException 400: If state token is expired or invalid or if fetching
        email from github fails or the email is already registered with a different auth_provider.
        HTTPException 500: If internal server error occurs.
    """

    github_provider = GithubAuthProvider()

    token_exchange_response = await github_provider.exchange_code_for_token(code, state)
    github_access_token = token_exchange_response.get("access_token")
    if not github_access_token:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Failed to exchange code for token.",
        )

    user_info = await github_provider.get_user_info(github_access_token)
    email = user_info.get("email")

    if not email:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Failed to retrieve email from github.",
        )

    user = await get_user_by_email(db, email)

    if user and user.auth_provider != AuthValues.GITHUB:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email is already registered with a different authentication provider.",
        )

    try:
        if not user:
            user_in = GithubUserCreate(
                email=email, password=None, auth_provider=AuthValues.GITHUB
            )
            user = await create_user(db, user_in)
            await db.commit()

        await db.refresh(user)
        access_token = create_access_token(subject=str(user.id))
        refresh_token = await create_refresh_token(user_id=str(user.id))
        return {
            "access_token": access_token,
            "refresh_token": refresh_token,
            "token_type": "bearer",
        }

    except HTTPException:
        raise
    except Exception as e:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An internal server error occurred.",
        )
